POST http://localhost:4001/cadastro
content-type: application/json

    {

        "nome": "Rodrigo Egos",
        "cpf": "400.289.221-90",
        "endereco": "Rua dos Bobos, 0"
    }

###

GET http://localhost:4001/usuarios

###
GET http://localhost:4001/deletar/4
###
PUT http://localhost:4001/vendas/ByGNa1Jbc
content-type: application/json

    {
        "cliente": {
            "nome": "Jdoão Marcos silva",
            "cpf": "000.000.000-00",
            "endereco": "Rua dos Bobos, 0"
        }
    }

###

DELETE http://localhost:4001/vendas/AIE8-vtv-
