POST http://localhost:4001/users/cadastrar
content-type: application/json

    {

        "nome": "Joao de barro",
        "cpf": "400.289.221-90",
        "endereco": "Rua dos Bobos, 0"
    }

###

GET http://localhost:4001/users/show

###
GET http://localhost:4001/users/deletar/6
