POST http://localhost:4001/login

###

GET http://localhost:4001/create

###
GET http://localhost:4001/vendas/ByGNa1Jbc
###
PUT http://localhost:4001/vendas/ByGNa1Jbc
content-type: application/json

    {
        "cliente": {
            "nome": "Jdoão Marcos silva",
            "cpf": "000.000.000-00",
            "endereco": "Rua dos Bobos, 0"
        }
    }

###

DELETE http://localhost:4001/vendas/AIE8-vtv-
